inventarioAnnaInn/inventario/urls.py
from django.urls import path 

from . import views

app_name = 'inventario'

urlpatterns = [
    
    path('', views.home, name = 'home'),
    
    #-----------------------COCINA----------------------------------------------------
    path('cocina/list/', views.CocinaListView.as_view(), name='cocina_list'),
    path('cocina/new/', views.CocinaCreateView.as_view(), name = 'cocina_new'),
    path('cocina/update/<int:pk>/', views.CocinaUpdateView.as_view(), name='cocina_update'),
    path('cocina/delete/<int:pk>/', views.CocinaDeleteView.as_view(), name='cocina_delete'),
    
    #-----------------------BLANCOS----------------------------------------------------
    path('blancos/list/', views.BlancosListView.as_view(), name='blancos_list'),
    path('blancos/new/', views.BlancosCreateView.as_view(), name = 'blancos_new'),
    path('blancos/update/<int:pk>/', views.BlancosUpdateView.as_view(), name='blancos_update'),
    path('blancos/delete/<int:pk>/', views.BlancosDeleteView.as_view(), name='blancos_delete'),
    
    #-----------------------INSUMOS----------------------------------------------------
    path('insumos/list/', views.InsumosListView.as_view(), name='insumo_list'),
    path('insumos/new/', views.InsumosCreateView.as_view(), name = 'insumos_new'),
    path('insumos/update/<int:pk>/', views.InsumosUpdateView.as_view(), name='insumos_update'),
    path('insumos/delete/<int:pk>/', views.InsumosDeleteView.as_view(), name='insumos_delete'),

]

inventarioAnnaInn/inventarioAnnaInn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hotel/', include('inventario.urls')),
    path('', include('login.urls')),
]

inventarioAnnaInn/login/urls.py
from django.urls import path 

from . import views 

urlpatterns = [
    path('', views.LoginFormView.as_view(), name = 'login'),
    path('logout/', views.LogoutView.as_view(next_page='login'), name = 'logout'),
]

inventarioAnnaInn/login/models.py
from django.db import models

# Create your models here.

inventarioAnnaInn/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, LogoutView

class LoginFormView(LoginView):
    template_name = 'login.html'

    def dispatch(self, request, *args, **kwargs):
        print(request.user)
        if request.user.is_authenticated:
            return redirect('home')
        return super().dispatch(request, *args, **kwargs)

inventarioAnnaInn/templates/inventario-blancos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href= "{% static 'css/inventario-insumos-style.css' %}">
    <title>Document</title>
</head>

<body>
    <header>
        <nav class="navbar-inventario">
            <div class="nav-leftside">
                <figure>
                    <img src="https://sp-ao.shortpixel.ai/client/q_glossy,ret_img/https://www.hotelannainn.com/wp-content/uploads/2019/05/logo-anna-in-blanco.png"
                        alt="logo" />
                </figure>
            </div>
            <div class="nav-middleside">
                <h1><b>INVENTARIO BLANCOS</b></h1>
            </div>
            <div class="nav-rightside">
                <ul class="nav-item-container">
                    <li>
                        <a href="./main.html"><img src="./icons/1564508_home_main_room_estate_property_icon.svg"
                                alt="home-icon" class="icon" /></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main>
        <aside class="inventario-aside">
            <a href="./inventarios.html"><b>Inventarios</b></a>
            <a href="./facturacion.html"><b>Facturacion</b></a>
            <a href="./reservaciones.html"><b>Reservaciones</b></a>
        </aside>
        <section>
            <!-- TOP BUTTONS -->
            <div class="top-buttons">
                <button type="button"> <a href="./registrar_entradac" target="_blank">Registrar Entrada</a></button>
                <button type="submit"> <a href="./registrar_salidac" target="_blank"> Registrar Salida</a></button>
            </div>
            
            <!-- SEARCH INPUT -->
            <div class="search-input">
                <input type="text" autocomplete="name" placeholder="Nombre Producto">
                <button type="submit">Buscar</button>
            </div>
            <br>
            <Center><h2>{{ title }}</h2></Center>
            <!-- TABLE -->
            <table id="inventario-insumos" class="inventario">
                <tr>
                    <th>ID</th>
                    <th>Producto</th>
                    <th>Proveedor</th>
                    <th>Subcategoria</th>
                    <th>Stock</th>
                    <th>Fecha</th>
                    <th>Acciones</th>
                </tr>

                {% for p in object_list %}
                <tr>
                    <td>{{ p.id }}</td>
                    <td>{{ p.producto }}</td>
                    <td>{{ p.proveedor }}</td>
                    <td>{{ p.subcategoria }}</td>
                    <td>{{ p.stock }}</td>
                    <td>{{ p.fecha }}</td> 
                    <td>
                        <a href="{% url 'inventario:blancos_update' p.id %}"> Editar </a>
                        <a href="{% url 'inventario:blancos_delete' p.id %}"> Eliminar </a>
                    </td>
                </tr>
                {% endfor %}
            </table>
            <!-- FIN TABLE -->

        </section>
    </main>
    <footer></footer>
</body>

</html>

inventarioAnnaInn/templates/inventario-cocina.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href= "{% static 'css/inventario-insumos-style.css' %}">
    <title>Document</title>
</head>

<body>
    <header>
        <nav class="navbar-inventario">
            <div class="nav-leftside">
                <figure>
                    <img src="https://sp-ao.shortpixel.ai/client/q_glossy,ret_img/https://www.hotelannainn.com/wp-content/uploads/2019/05/logo-anna-in-blanco.png"
                        alt="logo" />
                </figure>
            </div>
            <div class="nav-middleside">
                <h1><b>INVENTARIO COCINA</b></h1>
            </div>
            <div class="nav-rightside">
                <ul class="nav-item-container">
                    <li>
                        <a href="./main.html"><img src="./icons/1564508_home_main_room_estate_property_icon.svg"
                                alt="home-icon" class="icon" /></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main>
        <aside class="inventario-aside">
            <a href="./inventarios.html"><b>Inventarios</b></a>
            <a href="./facturacion.html"><b>Facturacion</b></a>
            <a href="./reservaciones.html"><b>Reservaciones</b></a>
        </aside>
        <section>
            <!-- TOP BUTTONS -->
            <div class="top-buttons">
                <button type="button"> <a href="./registrar_entradac" target="_blank">Registrar Entrada</a></button>
                <button type="submit"> <a href="./registrar_salidac" target="_blank"> Registrar Salida</a></button>
            </div>
            
            <!-- SEARCH INPUT -->
            <div class="search-input">
                <input type="text" autocomplete="name" placeholder="Nombre Producto">
                <button type="submit">Buscar</button>
            </div>
             <!-- TABLE -->
             <table id="inventario-insumos" class="inventario">
                <tr>
                    <th>ID</th>
                    <th>Producto</th>
                    <th>Proveedor</th>
                    <th>Subcategoria</th>
                    <th>Stock</th>
                    <th>Fecha</th>
                    <th>Acciones</th>
                </tr>

                {% for p in object_list %}
                <tr>
                    <td>{{ p.id }}</td>
                    <td>{{ p.producto }}</td>
                    <td>{{ p.proveedor }}</td>
                    <td>{{ p.subcategoria }}</td>
                    <td>{{ p.stock }}</td>
                    <td>{{ p.fecha }}</td>
                    <td>
                        <a href="{% url 'inventario:cocina_update' p.id %}"> Editar </a>
                        <a href="{% url 'inventario:cocina_delete' p.id %}"> Eliminar </a>
                    </td>
                </tr>
                {% endfor %}
            </table>
            <!-- FIN TABLE -->

            
        </section>
    </main>
    <footer></footer>
</body>

</html>

inventarioAnnaInn/templates/inventario-insumos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href= "{% static 'css/inventario-insumos-style.css' %}">
    <title>Document</title>
</head>

<body>
    <header>
        <nav class="navbar-inventario">
            <div class="nav-leftside">
                <figure>
                    <img src="https://sp-ao.shortpixel.ai/client/q_glossy,ret_img/https://www.hotelannainn.com/wp-content/uploads/2019/05/logo-anna-in-blanco.png"
                        alt="logo" />
                </figure>
            </div>
            <div class="nav-middleside">
                <h1><b>INVENTARIO INSUMOS</b></h1>
            </div>
            <div class="nav-rightside">
                <ul class="nav-item-container">
                    <li>
                        <a href="./main.html"><img src="./icons/1564508_home_main_room_estate_property_icon.svg"
                                alt="home-icon" class="icon" /></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main>
        <aside class="inventario-aside">
            <a href="./inventarios.html"><b>Inventarios</b></a>
            <a href="./facturacion.html"><b>Facturacion</b></a>
            <a href="./reservaciones.html"><b>Reservaciones</b></a>
        </aside>
        <section>
            <!-- TOP BUTTONS -->
            <div class="top-buttons">
                <button type="button"> <a href="./registrar_entrada" target="_blank">Registrar Entrada</a></button>
                <button type="submit"> <a href="./registrar_salida" target="_blank"> Registrar Salida</a></button>
            </div>
            
            <!-- SEARCH INPUT -->
            <div class="search-input">
                <input type="text" autocomplete="name" placeholder="Nombre Producto">
                <button type="submit">Buscar</button>
            </div>
            
            
            <!-- TABLE -->
            <table id="inventario-insumos" class="inventario">
                <tr>
                    <th>ID</th>
                    <th>Producto</th>
                    <th>Proveedor</th>
                    <th>Subcategoria</th>
                    <th>Stock</th>
                    <th>Fecha</th>
                    <th>Acciones</th>
                </tr>

                {% for p in object_list %}
                <tr>
                    <td>{{ p.id }}</td>
                    <td>{{ p.producto }}</td>
                    <td>{{ p.proveedor }}</td>
                    <td>{{ p.subcategoria }}</td>
                    <td>{{ p.stock }}</td>
                    <td>{{ p.fecha }}</td>
                    <td>
                        <a href="{% url 'inventario:insumos_update' p.id %}"> Editar </a>
                        <a href="{% url 'inventario:insumos_delete' p.id %}"> Eliminar </a>
                    </td>
                </tr>
                {% endfor %}
            </table>
            <!-- FIN TABLE -->

        </section>
    </main>
    <footer></footer>
</body>

</html>

inventarioAnnaInn/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href= "{% static 'css/login.css' %}">
    <link rel="stylesheet" href= "{% static 'css/tablet.css' %}" media="(min-width: 768px)">
    <link rel="stylesheet" href= "{% static 'css/laptop.css' %}" media="(min-width:1024px">

   
    <title>Document</title>
</head>
<body>
    <main>
        
        <section class="login-container">
            
            <div class="login-container--logo">
                <img src="https://sp-ao.shortpixel.ai/client/q_glossy,ret_img/https://www.hotelannainn.com/wp-content/uploads/2019/05/logo-anna-in-blanco.png" alt="hotel logo">
            </div>

            <div class="login--title">
                <h1>LOGIN</h1>
            </div>
            <div class="main-login--titles">
                <h1>LOGIN</h1>
                <p>Ingresar Usuario y Contraseña</p>
            </div>
            <div class="main-login--inputs">
                <input type="text" placeholder="Username">
                <input type="password" placeholder="Password">
                <p> <a href=""> ¿Olvidaste tu contraseña?</a></p>
            </div>
            <div class="main-login--button">
                <button type="submit">LOGIN</button>
            </div>
            <div class="main-login--footer">
                <p><a href="">Registrate</a></p>
            </div>
        </section>
    </main>
    
</body>
</html>

inventarioAnnaInn/templates/main.html
{% load static %}
<!DOCTYPE html>   
  <html lang="en">   
  <head>   
   <meta charset="UTF-8" />   
   <meta http-equiv="X-UA-Compatible" content="IE=edge" />   
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />   
   <title> Main Inventarios</title>
   <link rel="icon" href="https://sp-ao.shortpixel.ai/client/q_glossy,ret_img/https://www.hotelannainn.com/wp-content/uploads/2019/05/logo-anna-in-blanco.png" type="image/icon type">  

   <link rel="stylesheet" href= "{% static 'css/inventarios-style.css' %}">
   
  </head>   
  <body>   
   <div class="flex-container">  
       
     <div class="flex-slide home">  
       <div class="flex-title flex-title-home"><a href="inventario_insumos">Insumos </a></div>  
       
     </div>  
     <div class="flex-slide about">  
       <div class="flex-title"><a href="inventario_blancos">Blancos</a></div>  
       
     </div>  
 
     <div class="flex-slide contact">  
       <div class="flex-title"><a href="inventario_cocina">Cocina</a></div>  
           
     </div>  
   </div>  
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>  
   <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/769286/jquery.waitforimages.min.js"></script>  
  </body>   
  </html>   